/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_topd_Fibonacci */

#ifndef _Included_com_topd_Fibonacci
#define _Included_com_topd_Fibonacci
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_topd_Fibonacci
 * Method:    cal3
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_topd_Fibonacci_cal3
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
